

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.get;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sesca
 */
public class formulario extends javax.swing.JFrame {
 public static final String url = "jdbc:mysql://localhost:3306/notaestudiante";//link para conectar
    public static final String usuario = "root";
    public static final String pass = "";//<--si tiene contraseña, se coloca acá

    JFrame conect = new JFrame();
    Connection con = conect.getConnection();


    public formulario() {
        initComponents();
        botonguardar.setEnabled(false);
        botonnota.setEnabled(false);
        txmateria.addItem("");
        txmateria.addItem("Catedra Institucional");
        txmateria.addItem("Calculo Integral");
        txmateria.addItem("Programación III");



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txnombre = new javax.swing.JTextField();
        txnota1 = new javax.swing.JTextField();
        botonguardar = new javax.swing.JButton();
        txmateria = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        botonnota = new javax.swing.JButton();
        txnotafinal = new javax.swing.JFormattedTextField();
        txapellido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txmensaje = new javax.swing.JTextField();
        txmateria1 = new javax.swing.JTextField();
        txnota2 = new javax.swing.JTextField();
        txnota3 = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar notas"));

        jLabel1.setText("Nombres:");

        jLabel2.setText("Nota 1:");

        jLabel3.setText("Parcial: ");

        txnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txnombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txnombreKeyTyped(evt);
            }
        });

        txnota1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txnota1KeyReleased(evt);
            }
        });

        botonguardar.setText("Guardar datos");
        botonguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonguardarActionPerformed(evt);
            }
        });

        txmateria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txmateriaItemStateChanged(evt);
            }
        });
        txmateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txmateriaActionPerformed(evt);
            }
        });

        jLabel4.setText("Materia:");

        jLabel5.setText("Nota 2:");

        jLabel6.setText("Nota final:");

        jButton2.setText("Limpiar Datos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        botonnota.setText("Calcular nota final");
        botonnota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonnotaActionPerformed(evt);
            }
        });

        txnotafinal.setEditable(false);
        txnotafinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("### - ### ## ##"))));

        txapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txapellidoActionPerformed(evt);
            }
        });
        txapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txapellidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txapellidoKeyTyped(evt);
            }
        });

        jLabel7.setText("Apellidos:");

        txmensaje.setEditable(false);

        txmateria1.setEditable(false);

        txnota2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txnota2KeyReleased(evt);
            }
        });

        txnota3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txnota3KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(91, 91, 91))
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txnotafinal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txnota2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txnota3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel1))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txmateria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txapellido, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 4, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(botonnota, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txmateria1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(txmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txnota1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txmateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txnota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(txnota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txnota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txnotafinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(botonnota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txmateria1)
                    .addComponent(txmensaje))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonguardarActionPerformed

        String nombres = txnombre.getText();
        String apellidos = txapellido.getText();
        String materia = txmateria1.getText();
        double no1 = Double.valueOf(txnota1.getText());
        double no2 = Double.valueOf(txnota2.getText());
        double no3 = Double.valueOf(txnota3.getText());
        double nof = Double.valueOf(txnotafinal.getText());
        String ver = txmensaje.getText();
        

        Connection count = null;// cpunt es la variable
        count = getConnection();
        PreparedStatement var1;//preparar los resultados en la BD
        ResultSet rest;//mostrar resultados de la consulta de la BD

        try{
        var1 = count.prepareStatement("INSERT into nota(nombres,apellidos,materia,nota1,nota2,nota3,notafinal,veredicto)"
            + "values(?,?,?,?,?,?,?,?)");
        var1.setString(1, nombres);
        var1.setString(2, apellidos);
        var1.setString(3, materia);
        var1.setDouble(4, no1);
        var1.setDouble(5, no2);
        var1.setDouble(6, no3);
        var1.setDouble(7, nof);
        var1.setString(8, ver);

        var1.execute();

            JOptionPane.showMessageDialog(null,"Datos guardados.");


        }catch(SQLException ex){
            System.out.println(ex);
        }



    }//GEN-LAST:event_botonguardarActionPerformed

    private void txmateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txmateriaActionPerformed
    
    }//GEN-LAST:event_txmateriaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.txnombre.setText(""); 
        this.txapellido.setText("");      
        this.txnota1.setText("");
        this.txnota2.setText("");
        this.txnota3.setText("");
        this.txnotafinal.setText("");
        this.txmensaje.setText("");
        this.txmateria1.setText("");

        botonnota.setEnabled(false);
        botonguardar.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed



    private void botonnotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonnotaActionPerformed

        botonguardar.setEnabled(true);
        double notaf=0;
        double not1 = Double.valueOf(txnota1.getText());
        double not2 = Double.valueOf(txnota2.getText());
        double not3 = Double.valueOf(txnota3.getText());
        notaf=((not1+not2+not3)/3);
        this.txnotafinal.setText(""+(double)Math.round(notaf * 100d)/100);

        if(notaf>=3){
            this.txmensaje.setText("pasa");
        }else{
            this.txmensaje.setText("no pasa");}

    }//GEN-LAST:event_botonnotaActionPerformed

    public void validarcaracteres(java.awt.event.KeyEvent evento){
        if(evento.getKeyChar()>33 && evento.getKeyChar()<=64||
           evento.getKeyChar()>91 && evento.getKeyChar()<=96||
           evento.getKeyChar()>123 && evento.getKeyChar()<=208||
           evento.getKeyChar()>210 && evento.getKeyChar()<=240|| 
           evento.getKeyChar()>242 && evento.getKeyChar()<=255){
        evento.consume();
        JOptionPane.showMessageDialog(null,"No se permiten caracteres especiales en el nombre");
        }



}



    private void txmateriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txmateriaItemStateChanged
       String materia=(String) txmateria.getSelectedItem();
        if(materia.equals("Catedra Institucional")){
            this.txmateria1.setText("Catedra Institucional");
        }
        if(materia.equals("Calculo Integral")){
            this.txmateria1.setText("Calculo Integral");
        }
        if(materia.equals("Programación III")){
            this.txmateria1.setText("Programación III");
        }

        /*txmateria.addItem("");
        txmateria.addItem("Catedra Institucional");
        txmateria.addItem("Calculo Integral");
        txmateria.addItem("Programación III");*/
    }//GEN-LAST:event_txmateriaItemStateChanged

    private void txnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txnombreKeyReleased
            habo();  
            validarcaracteres(evt);      // TODO add your handling code here:
    }//GEN-LAST:event_txnombreKeyReleased

    private void txapellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txapellidoKeyReleased
habo();            // TODO add your handling code here:
    }//GEN-LAST:event_txapellidoKeyReleased

    private void txnota1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txnota1KeyReleased
     
    double notañ = Double.valueOf(txnota1.getText());

        if(notañ<0 ||notañ>5){
        JOptionPane.showMessageDialog(null,"la nota no puede ser menor a 0 ni mayor a 5");
        }

habo();


       // TODO add your handling code here:
    }//GEN-LAST:event_txnota1KeyReleased

    private void txnota2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txnota2KeyReleased
   

 double notañ = Double.valueOf(txnota2.getText());

        if(notañ<0 ||notañ>5){
        JOptionPane.showMessageDialog(null,"la nota no puede ser menor a 0 ni mayor a 5");
        }  

habo();       // TODO add your handling code here:
    }//GEN-LAST:event_txnota2KeyReleased

    private void txnota3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txnota3KeyReleased
  
 double notañ = Double.valueOf(txnota3.getText());

        if(notañ<0 ||notañ>5){
        JOptionPane.showMessageDialog(null,"la nota no puede ser menor a 0 ni mayor a 5");
        }  

habo();        // TODO add your handling code here:
    }//GEN-LAST:event_txnota3KeyReleased

    private void txnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txnombreKeyTyped
    validarcaracteres(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txnombreKeyTyped

    private void txapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txapellidoActionPerformed

    private void txapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txapellidoKeyTyped
validarcaracteres(evt);         // TODO add your handling code here:
    }//GEN-LAST:event_txapellidoKeyTyped

public void habo(){
        if(txnombre.getText().isEmpty()
            ||txapellido.getText().isEmpty()
            ||txnombre.getText().isEmpty()
            ||txnota1.getText().isEmpty()
            ||txnota2.getText().isEmpty()
            ||txnota3.getText().isEmpty()
            ||txmateria1.getText().isEmpty()){
            botonnota.setEnabled(false);

            }else{
            botonnota.setEnabled(true);}

}

public static Connection getConnection(){
    Connection var2 = null;
    try{
        Class.forName("com.mysql.cj.jdbc.Driver");//link de mysql para conectarnos
        var2 = (Connection) DriverManager.getConnection(url, usuario, pass);// realiza la conección con los datos de acceso para la sb
    }catch(Exception e){
        System.out.println(e);
    }
    return var2;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonguardar;
    private javax.swing.JButton botonnota;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txapellido;
    private javax.swing.JComboBox<String> txmateria;
    private javax.swing.JTextField txmateria1;
    private javax.swing.JTextField txmensaje;
    private javax.swing.JTextField txnombre;
    private javax.swing.JTextField txnota1;
    private javax.swing.JTextField txnota2;
    private javax.swing.JTextField txnota3;
    private javax.swing.JFormattedTextField txnotafinal;
    // End of variables declaration//GEN-END:variables
}
